Fix incomplete type & forward declaration GCC error
In file included from /usr/home/erik/Documents/Megapahit/viewer/indra/llcommon/lltrace.h:38,
                 from /usr/home/erik/Documents/Megapahit/viewer/indra/llcommon/llfasttimer.h:31,
                 from /usr/home/erik/Documents/Megapahit/viewer/indra/newview/llviewerprecompiledheaders.h:61,
                 from /usr/home/erik/Documents/Megapahit/viewer/build-linux-x86_64/newview/CMakeFiles/megapahit.dir/cmake_pch.hxx:5,
                 from <command-line>:
/usr/home/erik/Documents/Megapahit/viewer/indra/llcommon/llpointer.h: In instantiation of ‘void LLPointer<Type>::ref() [with Type = LLViewerObject]’:
/usr/home/erik/Documents/Megapahit/viewer/indra/llcommon/llpointer.h:60:9:   required from ‘LLPointer<Type>::LLPointer(Type*) [with Type = LLViewerObject]’
/usr/home/erik/Documents/Megapahit/viewer/indra/newview/llreflectionmap.h:127:47:   required from here
/usr/home/erik/Documents/Megapahit/viewer/indra/llcommon/llpointer.h:174:23: error: invalid use of incomplete type ‘class LLViewerObject’
  174 |             mPointer->ref();
      |             ~~~~~~~~~~^~~
In file included from /usr/home/erik/Documents/Megapahit/viewer/indra/newview/llviewerregion.h:45,
                 from /usr/home/erik/Documents/Megapahit/viewer/indra/newview/llagentlanguage.cpp:32:
/usr/home/erik/Documents/Megapahit/viewer/indra/newview/llreflectionmap.h:33:7: note: forward declaration of ‘class LLViewerObject’
   33 | class LLViewerObject;
      |       ^~~~~~~~~~~~~~
/usr/home/erik/Documents/Megapahit/viewer/indra/llcommon/llpointer.h: In instantiation of ‘void LLPointer<Type>::unref() [with Type = LLViewerObject]’:
/usr/home/erik/Documents/Megapahit/viewer/indra/llcommon/llpointer.h:92:9:   required from ‘LLPointer<Type>::~LLPointer() [with Type = LLViewerObject]’
/usr/home/erik/Documents/Megapahit/viewer/indra/newview/llreflectionmap.h:127:47:   required from here
/usr/home/erik/Documents/Megapahit/viewer/indra/llcommon/llpointer.h:184:19: error: invalid use of incomplete type ‘class LLViewerObject’
  184 |             temp->unref();
      |             ~~~~~~^~~~~
/usr/home/erik/Documents/Megapahit/viewer/indra/newview/llreflectionmap.h:33:7: note: forward declaration of ‘class LLViewerObject’
   33 | class LLViewerObject;
      |       ^~~~~~~~~~~~~~